apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ass3-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: cloud-ass3
  template:
    metadata:
      labels:
        app: cloud-ass3
    spec:
      containers:
      - name: cloud-ass3
        image: cloud_ass3  
        imagePullPolicy: Never